<a href="https://colab.research.google.com/github/poonamkhot123/Machine-Learning-Practice-Hub/blob/main/Day_26_Encoding_categorical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
df = pd.read_csv("/content/customer.csv")

In [29]:
df.sample(5)

    age  gender   review education purchased
0    30  Female  Average    School        No
30   73    Male  Average        UG        No
8    65  Female  Average        UG        No
44   77  Female  Average        UG        No
7    60  Female     Poor    School       Yes

In [30]:
df =df.iloc[:,2:]

In [31]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [32]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [34]:
X_train

     review education
39     Poor        PG
4   Average        UG
47     Good        PG
8   Average        UG
38     Good    School
28     Poor    School
49     Good        UG
36     Good        UG
2      Good        PG
34  Average    School
15     Poor        UG
27     Poor        PG
1      Poor        UG
25     Good    School
7      Poor    School
10     Good        UG
20  Average    School
44  Average        UG
29  Average        UG
45     Poor        PG
17     Poor        UG
14     Poor        PG
40     Good    School
41     Good        PG
21  Average        PG
42     Good        PG
35     Poor    School
32  Average        UG
3      Good        PG
30  Average        UG
19     Poor        PG
48     Good        UG
5   Average    School
24  Average        PG
13  Average    School
26     Poor        PG
6      Good    School
43     Poor        PG
22     Poor        PG
23     Good    School

In [35]:
y_train

39     No
4      No
47    Yes
8      No
38     No
28     No
49     No
36    Yes
2      No
34     No
15     No
27     No
1      No
25     No
7     Yes
10    Yes
20    Yes
44     No
29    Yes
45    Yes
17    Yes
14    Yes
40     No
41    Yes
21     No
42    Yes
35    Yes
32    Yes
3      No
30     No
19    Yes
48    Yes
5     Yes
24    Yes
13     No
26     No
6      No
43     No
22    Yes
23     No
Name: purchased, dtype: object

In [36]:
from sklearn.preprocessing import OrdinalEncoder

In [37]:
oe = OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [38]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [39]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [41]:
X_train

array([[0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.]])

In [42]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
le = LabelEncoder()

In [45]:
le.fit(y_train)

LabelEncoder()

In [46]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [47]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [48]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0])